"""SQLAlchemy database models."""
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean, Text,
    ForeignKey, Enum as SQLEnum, Date, Time, UniqueConstraint
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
from config.constants import (
    OrderStatus, OrderType, TradeStatus, SignalType,
    AgentName, Exchange
)

Base = declarative_base()


class Stock(Base):
    """Stock master table."""
    __tablename__ = "stocks"
    
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(50), unique=True, nullable=False, index=True)
    name = Column(String(200), nullable=False)
    exchange = Column(SQLEnum(Exchange), nullable=False, default=Exchange.NSE)
    sector = Column(String(100), nullable=True)
    market_cap = Column(Float, nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    market_data_daily = relationship("MarketDataDaily", back_populates="stock")
    market_data_intraday = relationship("MarketDataIntraday", back_populates="stock")
    screening_signals = relationship("ScreeningSignal", back_populates="stock")
    trades = relationship("Trade", back_populates="stock")
    orders = relationship("Order", back_populates="stock")
    portfolio = relationship("Portfolio", back_populates="stock")
    news_articles = relationship("NewsArticle", back_populates="stock")
    sentiment_scores = relationship("SentimentScore", back_populates="stock")


class MarketDataDaily(Base):
    """Daily market data with 29 technical indicators (2 years history)."""
    __tablename__ = "market_data_daily"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    
    # OHLCV
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)
    
    # Technical Indicators (29 indicators)
    rsi = Column(Float)
    macd = Column(Float)
    macd_signal = Column(Float)
    macd_histogram = Column(Float)
    bollinger_upper = Column(Float)
    bollinger_lower = Column(Float)
    bollinger_middle = Column(Float)
    sma_20 = Column(Float)
    sma_50 = Column(Float)
    sma_200 = Column(Float)
    ema_12 = Column(Float)
    ema_26 = Column(Float)
    ema_20 = Column(Float)
    ema_50 = Column(Float)
    adx = Column(Float)
    adx_positive = Column(Float)
    adx_negative = Column(Float)
    stochastic_k = Column(Float)
    stochastic_d = Column(Float)
    williams_r = Column(Float)
    cci = Column(Float)
    atr = Column(Float)
    obv = Column(Float)
    mfi = Column(Float)  # Money Flow Index
    volume_sma = Column(Float)
    price_change = Column(Float)
    price_change_percent = Column(Float)
    high_low_range = Column(Float)
    high_low_range_percent = Column(Float)
    volume_ratio = Column(Float)
    momentum = Column(Float)
    roc = Column(Float)  # Rate of Change
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    stock = relationship("Stock", back_populates="market_data_daily")
    
    __table_args__ = (
        UniqueConstraint('stock_id', 'date', name='uq_market_data_daily_stock_date'),
        {"sqlite_autoincrement": True},
    )


class MarketDataIntraday(Base):
    """Intraday market data (60 days, 1h bars)."""
    __tablename__ = "market_data_intraday"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    timestamp = Column(DateTime, nullable=False, index=True)
    interval = Column(String(10), default="1h", nullable=False)  # 1h, 5m, etc.
    
    # OHLCV
    open = Column(Float, nullable=False)
    high = Column(Float, nullable=False)
    low = Column(Float, nullable=False)
    close = Column(Float, nullable=False)
    volume = Column(Integer, nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    stock = relationship("Stock", back_populates="market_data_intraday")
    
    __table_args__ = (
        UniqueConstraint('stock_id', 'timestamp', 'interval', name='uq_market_data_intraday_stock_timestamp_interval'),
        {"sqlite_autoincrement": True},
    )


class ScreeningSignal(Base):
    """Screening signals generated by agents."""
    __tablename__ = "screening_signals"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    signal_type = Column(SQLEnum(SignalType), nullable=False)
    confidence_score = Column(Float, nullable=False)  # 0-100
    entry_price = Column(Float)
    stop_loss = Column(Float)
    target_price = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    # Relationships
    stock = relationship("Stock", back_populates="screening_signals")


class AgentDecision(Base):
    """Agent decisions and reasoning (audit trail)."""
    __tablename__ = "agent_decisions"
    
    id = Column(Integer, primary_key=True, index=True)
    agent_name = Column(SQLEnum(AgentName), nullable=False, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=True, index=True)
    decision_type = Column(String(100), nullable=False)  # e.g., "BUY_RECOMMENDATION", "SQL_QUERY"
    reasoning = Column(Text)  # LLM reasoning/explanation
    confidence_score = Column(Float)  # 0-100
    input_data = Column(Text)  # JSON string of input data
    output_data = Column(Text)  # JSON string of output data
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    # Relationships
    stock = relationship("Stock")


class Order(Base):
    """Orders with approval workflow."""
    __tablename__ = "orders"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    order_type = Column(SQLEnum(OrderType), nullable=False)
    quantity = Column(Integer, nullable=False)
    price = Column(Float)  # Limit price (if applicable)
    order_status = Column(SQLEnum(OrderStatus), default=OrderStatus.PENDING_APPROVAL, nullable=False, index=True)
    
    # Trade plan details
    entry_price = Column(Float)
    stop_loss = Column(Float)
    target_price = Column(Float)
    confidence_score = Column(Float)  # From strategy agent
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    approved_at = Column(DateTime, nullable=True)
    rejected_at = Column(DateTime, nullable=True)
    executed_at = Column(DateTime, nullable=True)
    
    # Execution details
    executed_price = Column(Float)
    execution_message = Column(Text)
    broker_order_id = Column(String(100), nullable=True)  # Shoonya/Upstox order ID
    
    # Relationships
    stock = relationship("Stock", back_populates="orders")
    trades = relationship("Trade", back_populates="order")


class Trade(Base):
    """Executed trades."""
    __tablename__ = "trades"
    
    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    buy_sell = Column(SQLEnum(OrderType), nullable=False)
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    stop_loss = Column(Float)
    target = Column(Float)
    pnl = Column(Float, default=0.0)
    pnl_percent = Column(Float, default=0.0)
    status = Column(SQLEnum(TradeStatus), default=TradeStatus.OPEN, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    executed_at = Column(DateTime, nullable=True)
    closed_at = Column(DateTime, nullable=True)
    
    # Relationships
    stock = relationship("Stock", back_populates="trades")
    order = relationship("Order", back_populates="trades")


class Portfolio(Base):
    """Current portfolio holdings."""
    __tablename__ = "portfolio"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), unique=True, nullable=False, index=True)
    quantity = Column(Integer, nullable=False, default=0)
    avg_price = Column(Float, nullable=False)
    current_price = Column(Float, nullable=False)
    unrealized_pnl = Column(Float, default=0.0)
    realized_pnl = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    stock = relationship("Stock", back_populates="portfolio")


class UserAction(Base):
    """User actions audit trail."""
    __tablename__ = "user_actions"
    
    id = Column(Integer, primary_key=True, index=True)
    action_type = Column(String(100), nullable=False, index=True)  # e.g., "APPROVE_ORDER", "REJECT_ORDER"
    details = Column(Text)  # JSON string with action details
    user_id = Column(String(100), nullable=True)  # Telegram user ID
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class PerformanceMetric(Base):
    """Performance metrics tracking."""
    __tablename__ = "performance_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    metric_name = Column(String(100), nullable=False, index=True)  # e.g., "total_pnl", "win_rate"
    value = Column(Float, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    metric_metadata = Column(Text)  # JSON string with additional data (renamed from 'metadata' to avoid SQLAlchemy conflict)


class TaxLedger(Base):
    """Tax ledger for compliance."""
    __tablename__ = "tax_ledger"
    
    id = Column(Integer, primary_key=True, index=True)
    trade_id = Column(Integer, ForeignKey("trades.id"), nullable=False, index=True)
    tax_type = Column(String(50), nullable=False)  # e.g., "STCG", "LTCG", "STT"
    amount = Column(Float, nullable=False)
    financial_year = Column(String(10), nullable=False, index=True)  # e.g., "2024-25"
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    trade = relationship("Trade")


class NewsArticle(Base):
    """News articles from various sources (30-day retention)."""
    __tablename__ = "news_articles"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=True, index=True)  # NULL for macro/news
    source = Column(String(100), nullable=False)  # 'economic_times', 'moneycontrol', etc.
    title = Column(String(500), nullable=False)
    content = Column(Text, nullable=False)  # Full article text
    url = Column(String(500), unique=True, nullable=False)
    published_date = Column(DateTime, nullable=False)
    category = Column(String(50), nullable=True)  # 'stock_specific', 'sector', 'macro', 'government', 'international'
    relevance_score = Column(Float, nullable=True)  # 0-1 (how relevant to trading)
    is_macro = Column(Boolean, default=False, nullable=False)
    macro_category = Column(String(100), nullable=True)  # 'rbi_rate_cut', 'gdp_growth', etc.
    affected_sectors = Column(Text, nullable=True)  # JSON array
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    stock = relationship("Stock", back_populates="news_articles")
    macro_sentiment_mappings = relationship("MacroStockSentiment", back_populates="news_article")


class SentimentScore(Base):
    """Daily aggregated sentiment scores per stock."""
    __tablename__ = "sentiment_scores"
    
    id = Column(Integer, primary_key=True, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=True, index=True)  # NULL for market-wide sentiment
    date = Column(Date, nullable=False, index=True)
    
    # Sentiment metrics
    overall_sentiment = Column(Float, nullable=False)  # -1 (bearish) to +1 (bullish)
    confidence = Column(Float, nullable=False)  # 0-1 (how confident in sentiment)
    article_count = Column(Integer, default=0, nullable=False)  # Number of articles analyzed
    
    # Sentiment breakdown
    positive_count = Column(Integer, default=0, nullable=False)
    negative_count = Column(Integer, default=0, nullable=False)
    neutral_count = Column(Integer, default=0, nullable=False)
    
    # Category-specific sentiment
    stock_specific_sentiment = Column(Float, nullable=True)  # News about this stock
    sector_sentiment = Column(Float, nullable=True)  # News about sector
    macro_sentiment = Column(Float, nullable=True)  # Macro economic news
    government_sentiment = Column(Float, nullable=True)  # Government policy news
    international_sentiment = Column(Float, nullable=True)  # International trade news
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    stock = relationship("Stock", back_populates="sentiment_scores")
    
    __table_args__ = (
        UniqueConstraint('stock_id', 'date', name='uq_sentiment_scores_stock_date'),
        {"sqlite_autoincrement": True},
    )


class MacroStockSentiment(Base):
    """Mapping of macro news to individual stock sentiment."""
    __tablename__ = "macro_stock_sentiment"
    
    id = Column(Integer, primary_key=True, index=True)
    news_article_id = Column(Integer, ForeignKey("news_articles.id"), nullable=False, index=True)
    stock_id = Column(Integer, ForeignKey("stocks.id"), nullable=False, index=True)
    macro_sentiment = Column(Float, nullable=False)  # Original macro sentiment
    sector_impact = Column(Float, nullable=False)  # Sector-level impact
    stock_sentiment = Column(Float, nullable=False)  # Final stock-specific sentiment
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    news_article = relationship("NewsArticle", back_populates="macro_sentiment_mappings")
    stock = relationship("Stock")


class NewsSource(Base):
    """Configuration for news sources."""
    __tablename__ = "news_sources"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)  # 'economic_times', 'moneycontrol'
    url_pattern = Column(String(500), nullable=False)  # RSS/API endpoint
    api_key = Column(String(200), nullable=True)  # If required
    is_active = Column(Boolean, default=True, nullable=False)
    fetch_frequency = Column(Integer, default=15, nullable=False)  # minutes
    last_fetched = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class Nifty500Sector(Base):
    """Nifty 500 sector and industry reference data."""
    __tablename__ = "nifty500_sectors"
    
    symbol = Column(String(50), primary_key=True)
    name = Column(String(200), nullable=False)
    sector = Column(String(100), nullable=True, index=True)
    industry = Column(String(100), nullable=True, index=True)
    market_cap_rank = Column(Integer, nullable=True)
